# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "ec8cea9a026f8ad91a318ebfb6237de4"
name = "online-store"
handle = "online-store-56"
application_url = "https://speech-network-ampland-highs.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products"

[auth]
redirect_urls = [
  "https://speech-network-ampland-highs.trycloudflare.com/auth/callback",
  "https://speech-network-ampland-highs.trycloudflare.com/auth/shopify/callback",
  "https://speech-network-ampland-highs.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
